### ISSUE TITLE
Minimum Dart version is too high

### ISSUE THREAD

**Issue by britannio** [bsutton/fixed#6]
The minimum Dart version supported by this package is 2.14.4. Does the package use any language features that are not supported in earlier versions? If not,  v2.12.0 would be ideal as any version before it doesn't support null safety.

https://github.com/bsutton/fixed/blob/main/pubspec.yaml#L7

**Comment by bsutton** [comment]
I've just pushed 1.0.3.

The dart Moon is now 2.12.

**Comment by britannio** [comment]
Thanks!
