### ISSUE TITLE
build fails (flutter Web) 

### ISSUE THREAD

**Issue by niklasbartsch** [bsutton/fixed#7]
My Flutter Web build fails because of fixed: 

<img width="760" alt="Bildschirmfoto 2021-12-20 um 12 49 31" src="https://user-images.githubusercontent.com/32355097/146763021-ccdd6481-35df-4b80-a938-a8a41fbe76ab.png">

**Comment by bsutton** [comment]
I've just released 1.1.0 which should have a fix for this.

Thanks for reporting the bug.

If it is still an issue feel free to re-open this issue.
